### ISSUE TITLE
docker-compose.yml broken: Tabs at end of lines, rejected by docker-compose

### ISSUE THREAD

**Issue by NuclearManD** [cartesi/compute-tutorials#54]
System: x86-64 Linux Mint laptop

uname -a output:
```
Linux nuclaer-machine 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Docker compose version: `docker-compose version 1.17.1, build unknown`

I'm getting the following error:
```
nuclaer@nuclaer-machine:~/gitrepos/Cartesi/compute-tutorials/compute-env$ docker-compose up
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 168, column 37
```

I've removed the tabs at the end of lines 168 and 176, and one other line I forget which.  I've done this in my fork of this repository, and will make a PR shortly.  I am not getting the error after these trivial changes to the file.

**Comment by stskeeps** [comment]
Could I ask you to check docker-compose --version and 'docker compose version'?

Should be Docker Compose version v2 at least.

**Comment by NuclearManD** [comment]
Hmm, that could be the issue.  The version is 1.17.1. `docker compose version` reports that `compose` is not a docker command.

Another machine I have has version 1.25.0, and I installed docker-compose only days ago.  Docker version is 1.5-2 (as reported by apt when I try to update).  It also reports that `compose` is not a docker command.  These versions are from official debian repositories.  My build is new enough that I would expect many people use these versions still.  Nonetheless, I don't think we should have whitespace at the end of lines.

**Comment by stskeeps** [comment]
You're right! Just wanted to understand how the hell it got past QA :)

**Comment by NuclearManD** [comment]
Ah, yea that makes sense.  Somehow the bugs always find their way through XD  Thank you
